### ISSUE TITLE
take a decision to implement UI of native client appication.

### ISSUE THREAD

**Issue by anil235476** [Taha39/webRTC_client#10]
We have to decide UI technology. 
  I will suggest following design and technologies:-

 > login UI should be an separate application, after login success another application should be launched with required information of signalling given to that application as command line argument by login application.
>Following technology can be thought of, it cons pros should be considered:-
(1) QT.
(2) Windows 
(3) chromium embedded framework.

**Comment by anil235476** [comment]
We will have UI application separate, and another process for backend.
WE decided to give 1 week to build a prototype using CEF and will review it to take final decision.
on 09 March. 
Anil will make a protype.

**Comment by anil235476** [comment]
not able to look into this.
forwarding deadline it to next week. i.e 16 march

**Comment by Taha39** [comment]
we have build CEF. however, needs integration of renderer with it.
Taha will do this .

**Comment by anil235476** [comment]
we have decided to use chromium embeded framework
