### ISSUE TITLE
support of camera capture and rendering 

### ISSUE THREAD

**Issue by anil235476** [Taha39/webRTC_client#11]

**Comment by anil235476** [comment]
Anil will check the interface part to plug renderer.
Taha will add yuv render into existing video renderer.
Anil will check camera capture functionality in webrtc. 
After above work Taha will integrate.

**Comment by anil235476** [comment]
added camera capture and support to make video track.
however, on browser client, not able to see any video rendering..
need to check by making a

**Comment by anil235476** [comment]
unit test for camera capture and render has been developed and it is working.
however, some issue still occur sometime when capturing gets start.
I think that is required some effort in debugging.
I leave it on Taha to debug issue.

**Comment by Taha39** [comment]
rendering is working fine.
There is some issue in camera capture module that have to be looked into. Taha will do that.

**Comment by Taha39** [comment]
Done some changes to make rendering app work without issue. Now rendering_app application is working good, but not able to figure out why there is crash when using sink class.

**Comment by Taha39** [comment]
it is done. might be some issue of crash which was the reason of c++17 and c++11 mismatch between webrtc source and our source
